spring:
  datasource:
    url: jdbc:mysql://localhost:3306/final_project_ea?useSSL=false&serverTimezone=UTC
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        registration:
          google:
            provider:
            client-id:
            client-secret:
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/google"
            scope:
              - openid
              - profile
              - email
            client-name: Login with Google
        provider:
          google:
            issuer-uri: https://accounts.google.com
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token

  profiles:
    active: prod
